Update bun version

diff --git a/.github/workflows/test_bun_versions.yml b/.github/workflows/test_bun_versions.yml
--- a/.github/workflows/test_bun_versions.yml
+++ b/.github/workflows/test_bun_versions.yml
@@ -22,21 +22,29 @@ jobs:
           export BUN_INSTALL="$HOME/.bun"
           curl -fsSL https://bun.com/install | bash -s "bun-v$bun_version"
           export PATH="$HOME/.bun/bin:$PATH"
+          echo "Bun version: $(bun --version)"
 
       - name: Install Dependencies
         id: install-deps
         run: |
           export PATH="$HOME/.bun/bin:$PATH"
+          echo "Bun version: $(bun --version)"
           bun install
 
       - name: Run Tests
         id: run-tests
         run: |
           export PATH="$HOME/.bun/bin:$PATH"
-          bun bw test
+          echo "Bun version: $(bun --version)"
+          bun bw test --reporter=junit --reporter-output=j../../junit.xml
+          if grep -q "<skipped" junit.xml; then
+            echo "❌ Skipped tests found. Exiting with error."
+            exit 1
+          fi
 
       - name: Run Tests Against Build
         id: run-tests-against-build
         run: |
           export PATH="$HOME/.bun/bin:$PATH"
+          echo "Bun version: $(bun --version)"
           bun bw build:test
diff --git a/.github/workflows/validate_code.yml b/.github/workflows/validate_code.yml
--- a/.github/workflows/validate_code.yml
+++ b/.github/workflows/validate_code.yml
@@ -46,7 +46,12 @@ jobs:
         uses: ./.github/actions/setup
       - name: Run Tests
         id: test
-        run: bun --cwd=./packages/bun-workspaces test
+        run: |
+          bun --cwd=./packages/bun-workspaces test --reporter=junit --reporter-output=j../../junit.xml
+          if grep -q "<skipped" junit.xml; then
+            echo "❌ Skipped tests found. Exiting with error."
+            exit 1
+          fi
 
   test_build:
     name: Run Tests Against Build
